In [3]:
import numpy as np

two_dimensional_list = [[0,1,2], [3,4,5], [6,7,8]]
numpy_two_dimensional_list = np.array(two_dimensional_list)
print(type (numpy_two_dimensional_list))
print(numpy_two_dimensional_list)

<class 'numpy.ndarray'>
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [3]:
# Numpy array from tuple
# Creating tuple in Python
python_tuple = (1,2,3,4,5)
print(type (python_tuple)) # <class 'tuple'>
print('python_tuple: ', python_tuple) # python_tuple:  (1, 2, 3, 4, 5)

numpy_array_from_tuple = np.array(python_tuple)
print(type (numpy_array_from_tuple)) # <class 'numpy.ndarray'>
print('numpy_array_from_tuple: ', numpy_array_from_tuple) # numpy_array_from_tuple:  [1 2 3 4 5]

<class 'tuple'>
python_tuple:  (1, 2, 3, 4, 5)
<class 'numpy.ndarray'>
numpy_array_from_tuple:  [1 2 3 4 5]


In [4]:
nums = np.array([1, 2, 3, 4, 5])
print(nums)
print('shape of nums: ', nums.shape)
print(numpy_two_dimensional_list)
print('shape of numpy_two_dimensional_list: ', numpy_two_dimensional_list.shape)
three_by_four_array = np.array([[0, 1, 2, 3],
        [4,5,6,7],
        [8,9,10, 11]])
print(three_by_four_array.shape)

[1 2 3 4 5]
shape of nums:  (5,)
[[0 1 2]
 [3 4 5]
 [6 7 8]]
shape of numpy_two_dimensional_list:  (3, 3)
(3, 4)


In [5]:
# Mathematical Operation
# Addition
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
print('original array: ', numpy_array_from_list)
ten_plus_original = numpy_array_from_list  + 10
print(ten_plus_original)


original array:  [1 2 3 4 5]
[11 12 13 14 15]


In [6]:
two_dimension_array = np.array([[1,2,3],[4,5,6], [7,8,9]])
two_dimension_array[::-1,::-1]

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [4]:
# Numpy Zeroes
numpy_ones = np.ones((3,3),dtype=int,order='C')
print(numpy_ones)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [7]:
twoes = numpy_ones * 2
twoes

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [8]:
# Reshape
# numpy.reshape(), numpy.flatten()
first_shape  = np.array([(1,2,3), (4,5,6)])
print(first_shape)
reshaped = first_shape.reshape(3,2)
print(reshaped)


[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [9]:
flattened = reshaped.flatten()
flattened

array([1, 2, 3, 4, 5, 6])

In [10]:
    ## Horitzontal Stack
np_list_one = np.array([1,2,3])
np_list_two = np.array([4,5,6])

print(np_list_one + np_list_two)

print('Horizontal Append:', np.hstack((np_list_one, np_list_two)))

[5 7 9]
Horizontal Append: [1 2 3 4 5 6]


In [11]:
    ## Vertical Stack
print('Vertical Append:', np.vstack((np_list_one, np_list_two)))

Vertical Append: [[1 2 3]
 [4 5 6]]


In [12]:
    # np.random.normal(mu, sigma, size)
normal_array = np.random.normal(79, 15, 80)
normal_array


array([ 83.6885275 ,  99.85841272,  81.39077648,  88.68442567,
        52.85624632,  54.32899649,  70.54490782,  79.75603434,
        85.73495772,  66.68046821,  68.25791187,  77.3003827 ,
        90.46154446,  75.75253024,  73.65415836,  66.03813098,
        92.20790577,  85.63300107,  86.4626041 ,  85.46735549,
        73.0054202 , 103.26397123,  91.75057678,  68.06003027,
        78.95831927,  60.37646446,  83.98096027,  92.98212168,
        92.06855625,  53.16496031,  56.32192017,  89.2627199 ,
        98.8489601 ,  87.23926296,  91.53906479,  64.01616026,
        68.56302806,  72.37988953,  70.58994005,  57.39538991,
        70.55309317,  55.05186837,  91.06909078,  60.42591352,
        90.63481227,  86.98417564,  79.1130186 ,  69.70431781,
        57.55094907,  66.99193783,  66.9104461 ,  82.67996341,
        71.67325633,  86.17278166,  77.84707982,  54.29096489,
        75.75861319, 107.96001842,  87.65535119,  87.17629338,
        92.94643215,  91.92886505,  72.29605579,  56.51